export enum COIN_SHORTCODE {
  BTCUSDT = "BTC",
  ETHUSDT = "ETH",
  MATICUSDT = "MATIC",
  BNBUSDT = "BNB",
  USDCUSDT = "USDC",
  AVAXUSDT = "AVAX",
  SOLUSDT = "SOL",
  TRXUSDT = "TRX",
  APEUSDT = "APE",
  SHIBUSDT = "SHIB",
  LINKUSDT = "LINK",
  MANABUSDT = "MANA",
  SANDUSDT = "SAND",
  CHZUSDT = "CHZ",
  AXSUSDT = "AXS",
  GALAUSDT = "GALA",
  USDYUSDT = "USDY",
  FLOKIUSDT = "FLOKI",
  PEPEUSDT = "PEPE",
  UNIUSDT = "UNI",
}

export enum COIN_NAME {
  BTCUSDT = "Bitcoin",
  ETHUSDT = "Ethereum",
  MATICUSDT = "Polygon",
  BNBUSDT = "Binance Coin",
  USDCUSDT = "USD Coin",
  AVAXUSDT = "Avalanche",
  SOLUSDT = "Solana",
  TRXUSDT = "Tron",
  APEUSDT = "ApeCoin",
  SHIBUSDT = "Shiba Inu",
  LINKUSDT = "Chainlink",
  MANABUSDT = "Decentraland",
  SANDUSDT = "The Sandbox",
  CHZUSDT = "Chiliz",
  AXSUSDT = "Axie Infinity",
  GALAUSDT = "Gala",
  USDYUSDT = "Ondo US Dollar Yield",
  FLOKIUSDT = "Floki Inu",
  PEPEUSDT = "Pepe Coin",
  UNIUSDT = "Uniswap",
}
